<a href="https://colab.research.google.com/github/Pratikshapawar-star/python-internship-practice-code/blob/main/Day_3_nba_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv("nba.csv")
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df.shape)

(458, 9)

In [ ]:
print(df.size)

4122

In [ ]:
print(len(df))

458

In [ ]:
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(104)

In [ ]:
df.loc[0:4,:]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [ ]:
df.loc[0:4,["Name","Team"]]

            Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [ ]:
#use iloc method to select the first five row
df.iloc[0:4,:]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

In [ ]:
df.iloc[90:100,1:5]

                     Team  Number Position   Age
90  Golden State Warriors    18.0       PF  33.0
91   Los Angeles Clippers    45.0        C  27.0
92   Los Angeles Clippers    19.0       PF  29.0
93   Los Angeles Clippers    11.0       SG  36.0
94   Los Angeles Clippers    22.0       SF  23.0
95   Los Angeles Clippers     8.0       SF  29.0
96   Los Angeles Clippers    32.0       PF  27.0
97   Los Angeles Clippers    33.0       SF  28.0
98   Los Angeles Clippers     6.0        C  27.0
99   Los Angeles Clippers    12.0       PF  29.0

In [ ]:
sub_df=df[["Name","Team","Number","College"]]
sub_df

              Name            Team  Number            College
0    Avery Bradley  Boston Celtics     0.0              Texas
1      Jae Crowder  Boston Celtics    99.0          Marquette
2     John Holland  Boston Celtics    30.0  Boston University
3      R.J. Hunter  Boston Celtics    28.0      Georgia State
4    Jonas Jerebko  Boston Celtics     8.0                NaN
..             ...             ...     ...                ...
453   Shelvin Mack       Utah Jazz     8.0             Butler
454      Raul Neto       Utah Jazz    25.0                NaN
455   Tibor Pleiss       Utah Jazz    21.0                NaN
456    Jeff Withey       Utah Jazz    24.0             Kansas
457            NaN             NaN     NaN                NaN

[458 rows x 4 columns]

In [ ]:
df[df["College"]=="Texas"]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

In [ ]:
df[df["College"]=="Kansas"]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
49,Joel Embiid,Philadelphia 76ers,21.0,C,22.0,7-0,250.0,Kansas,4626960.0
87,Brandon Rush,Golden State Warriors,4.0,SF,30.0,6-6,220.0,Kansas,1270964.0
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3376000.0
107,Tarik Black,Los Angeles Lakers,28.0,C,24.0,6-9,250.0,Kansas,845059.0
148,Ben McLemore,Sacramento Kings,23.0,SG,23.0,6-5,195.0,Kansas,3156600.0
173,Sasha Kaun,Cleveland Cavaliers,14.0,C,31.0,6-11,260.0,Kansas,1276000.0
194,Marcus Morris,Detroit Pistons,13.0,PF,26.0,6-9,235.0,Kansas,5000000.0
311,Kirk Hinrich,Atlanta Hawks,12.0,SG,35.0,6-4,190.0,Kansas,2854940.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000.0
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240.0
383,Darrell Arthur,Denver Nuggets,0.0,PF,28.0,6-9,235.0,Kansas,2814000.0
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [ ]:
df[df["Position"]=="PF"]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
...,...,...,...,...,...,...,...,...,...
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0

In [ ]:
df_filltered=df[(df["College"]=="Texas")&(df["Age"]<25)]
df_filltered

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0

In [ ]:
df_filltered=df[(df["College"]=="Boston University")&(df["Age"]<25)]
df_filltered

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

In [ ]:
df.query("Age>30")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

In [ ]:
df.query("College >'Texas'")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
...,...,...,...,...,...,...,...,...,...
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0

In [ ]:
clean_df=df.dropna(axis=0,how="any")
clean_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [ ]:
#drop rows that have less than 8 non-missing values
clean_df=df.dropna(axis=0,thresh=8)
clean_df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [ ]:
df_clean=df.dropna(axis=1)
df_clean

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[458 rows x 0 columns]

In [ ]:
df["Salary"].isnull().sum()

np.int64(12)

In [ ]:
avg_salary=df["Salary"].mean()
avg_salary

np.float64(4842684.105381166)

In [ ]:
import warnings
warnings.filterwarnings("ignore")
df["Salary"].fillna(value=avg_salary,inplace=True)

In [ ]:
df["Salary"].isnull().sum()

np.int64(0)

Exercies 8

In [ ]:
data={
    "Name":["Aman","Ram","Aman","Ram","Aman"],
    "Age":[27,24,27,24,19],
    "City":["Haryana","surat","Haryana","New Delhi","Rajkot"]
}
df=pd.DataFrame(data)
print(df)
print("\n",df.duplicated())

   Name  Age       City
0  Aman   27    Haryana
1   Ram   24      surat
2  Aman   27    Haryana
3   Ram   24  New Delhi
4  Aman   19     Rajkot

 0    False
1    False
2     True
3    False
4    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
#check for duplicate entries in columns Name and Age
print(df.duplicated(subset=["Name","Age"]))

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [ ]:
#remove duplicates
df.drop_duplicates(inplace=True)
df

   Name  Age       City
0  Aman   27    Haryana
1   Ram   24      surat
3   Ram   24  New Delhi
4  Aman   19     Rajkot

Exercies 9

In [ ]:
#drop null values
df.dropna(axis=0,inplace=True)
df.shape

(4, 3)

In [ ]:
result=df.groupby("College")
result

In [ ]:
result.get_group("Texas")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

In [ ]:
result["Age"].mean().sort_values(ascending=True)

College
Bowling Green          22.0
Georgia State          22.0
Louisiana-Lafayette    22.0
Iowa State             23.0
Georgia                23.0
                       ...
Utah Valley            32.0
Western Carolina       33.0
Central Michigan       34.0
Xavier                 35.0
Blinn College          37.0
Name: Age, Length: 118, dtype: float64

In [ ]:
count_college_wise=result["Team"].count()
count_college_wise

College
Alabama              3
Arizona             13
Arizona State        2
Arkansas             3
Baylor               1
                    ..
Western Michigan     1
Wichita State        1
Wisconsin            5
Wyoming              1
Xavier               1
Name: Team, Length: 118, dtype: int64

In [ ]:
result.agg(
    avg_age=("Age", "mean"),
    coult_college=("College","count")
)

                    avg_age  coult_college
College
Alabama           29.000000              3
Arizona           27.384615             13
Arizona State     27.500000              2
Arkansas          27.333333              3
Baylor            25.000000              1
...                     ...            ...
Western Michigan  25.000000              1
Wichita State     25.000000              1
Wisconsin         25.800000              5
Wyoming           23.000000              1
Xavier            35.000000              1

[118 rows x 2 columns]

Exercise 10

In [ ]:
import pandas as pd
data={
    "Maths":[90, 85,98,80,55,78],
    "Science":[92,87,59,64,87,96], "English":[95,94,84,75,67,65]
}
df=pd.DataFrame(data)
print("DataFrame = \n",df)

print("\nSum=\n",df.sum())
print("\nMaximum Marks = \n", df.max())

print("\nMedian = \n",df.median())
print("\nMean = \n",df.mean())

DataFrame =
    Maths  Science  English
0     90       92       95
1     85       87       94
2     98       59       84
3     80       64       75
4     55       87       67
5     78       96       65

Sum=
 Maths      486
Science    485
English    480
dtype: int64

Maximum Marks =
 Maths      98
Science    96
English    95
dtype: int64

Median =
 Maths      82.5
Science    87.0
English    79.5
dtype: float64

Mean =
 Maths      81.000000
Science    80.833333
English    80.000000
dtype: float64